package vp.magisterski.model.enumerations;

public enum AppRole {
    PROFESSOR, ADMIN, GUEST, STUDENT,
    ACADEMIC_AFFAIR_VICE_DEAN,
    SCIENCE_AND_COOPERATION_VICE_DEAN,
    FINANCES_VICE_DEAN,
    DEAN,
    STUDENT_ADMINISTRATION,
    STUDENT_ADMINISTRATION_MANAGER,
    FINANCE_ADMINISTRATION,
    FINANCE_ADMINISTRATION_MANAGER,
    LEGAL_ADMINISTRATION,
    ARCHIVE_ADMINISTRATION,
    ADMINISTRATION_MANAGER,
    EXTERNAL;

    public String roleName() {
        return "ROLE_" + this.name();
    }
}
